package net.runelite.client.plugins.ipowerskiller;

public enum iPowerSkillerState {
    ANIMATING,
    BANK_NOT_FOUND,
    DEPOSIT_ALL,
    DEPOSIT_EXCEPT,
    DEPOSIT_ITEMS,
    DROP_ALL,
    DROP_EXCEPT,
    DROP_ITEMS,
    FIND_BANK,
    FIND_GAME_OBJECT,
    FIND_NPC,
    FIND_WALL,
    HANDLE_BREAK,
    INVALID_DROP_IDS,
    ITERATING,
    MISSING_ITEMS,
    MOVING,
    RETURN_SAFE_SPOT,
    TIMEOUT,
    WAIT_DENSE_ESSENCE,
    ADDING_SANDSTONE_TO_GRINDER,
    WALKING_BACK_TO_SANDSTONE,
    CASTING_HUMIDIFY;
}
