package net.runelite.client.plugins.combinationrunecrafter;

public enum CombinationRunecrafterState
{
	ACTION_ITEM,
	DEPOSIT_ALL,
	DEPOSIT_ALL_EXCEPT,
	ENTER_MYSTERIOUS_RUINS,
	ITERATING,
	MOVING,
	OPEN_BANK,
	OUT_OF_AREA,
	OUT_OF_ITEM,
	SET_TALISMAN,
	TELEPORT_CASTLE_WARS,
	TELEPORT_DUEL_ARENA,
	TIMEOUT,
	USE_FIRE_ALTAR,
	WITHDRAW_ALL_ITEM,
	WITHDRAW_ITEM;
}
